lib: [
  "_build/install/default/lib/Lua/META"
  "_build/install/default/lib/Lua/Parser/common.ml" {"Parser/common.ml"}
  "_build/install/default/lib/Lua/Parser/common.mli" {"Parser/common.mli"}
  "_build/install/default/lib/Lua/Parser/expr.ml" {"Parser/expr.ml"}
  "_build/install/default/lib/Lua/Parser/expr.mli" {"Parser/expr.mli"}
  "_build/install/default/lib/Lua/Parser/parser.a" {"Parser/parser.a"}
  "_build/install/default/lib/Lua/Parser/parser.cma" {"Parser/parser.cma"}
  "_build/install/default/lib/Lua/Parser/parser.cmi" {"Parser/parser.cmi"}
  "_build/install/default/lib/Lua/Parser/parser.cmt" {"Parser/parser.cmt"}
  "_build/install/default/lib/Lua/Parser/parser.cmti" {"Parser/parser.cmti"}
  "_build/install/default/lib/Lua/Parser/parser.cmx" {"Parser/parser.cmx"}
  "_build/install/default/lib/Lua/Parser/parser.cmxa" {"Parser/parser.cmxa"}
  "_build/install/default/lib/Lua/Parser/parser.ml" {"Parser/parser.ml"}
  "_build/install/default/lib/Lua/Parser/parser.mli" {"Parser/parser.mli"}
  "_build/install/default/lib/Lua/Parser/parser__.cmi" {"Parser/parser__.cmi"}
  "_build/install/default/lib/Lua/Parser/parser__.cmt" {"Parser/parser__.cmt"}
  "_build/install/default/lib/Lua/Parser/parser__.cmx" {"Parser/parser__.cmx"}
  "_build/install/default/lib/Lua/Parser/parser__.ml" {"Parser/parser__.ml"}
  "_build/install/default/lib/Lua/Parser/parser__Common.cmi" {"Parser/parser__Common.cmi"}
  "_build/install/default/lib/Lua/Parser/parser__Common.cmt" {"Parser/parser__Common.cmt"}
  "_build/install/default/lib/Lua/Parser/parser__Common.cmti" {"Parser/parser__Common.cmti"}
  "_build/install/default/lib/Lua/Parser/parser__Common.cmx" {"Parser/parser__Common.cmx"}
  "_build/install/default/lib/Lua/Parser/parser__Expr.cmi" {"Parser/parser__Expr.cmi"}
  "_build/install/default/lib/Lua/Parser/parser__Expr.cmt" {"Parser/parser__Expr.cmt"}
  "_build/install/default/lib/Lua/Parser/parser__Expr.cmti" {"Parser/parser__Expr.cmti"}
  "_build/install/default/lib/Lua/Parser/parser__Expr.cmx" {"Parser/parser__Expr.cmx"}
  "_build/install/default/lib/Lua/Parser/parser__Stat.cmi" {"Parser/parser__Stat.cmi"}
  "_build/install/default/lib/Lua/Parser/parser__Stat.cmt" {"Parser/parser__Stat.cmt"}
  "_build/install/default/lib/Lua/Parser/parser__Stat.cmti" {"Parser/parser__Stat.cmti"}
  "_build/install/default/lib/Lua/Parser/parser__Stat.cmx" {"Parser/parser__Stat.cmx"}
  "_build/install/default/lib/Lua/Parser/stat.ml" {"Parser/stat.ml"}
  "_build/install/default/lib/Lua/Parser/stat.mli" {"Parser/stat.mli"}
  "_build/install/default/lib/Lua/ast/ast.a" {"ast/ast.a"}
  "_build/install/default/lib/Lua/ast/ast.cma" {"ast/ast.cma"}
  "_build/install/default/lib/Lua/ast/ast.cmi" {"ast/ast.cmi"}
  "_build/install/default/lib/Lua/ast/ast.cmt" {"ast/ast.cmt"}
  "_build/install/default/lib/Lua/ast/ast.cmx" {"ast/ast.cmx"}
  "_build/install/default/lib/Lua/ast/ast.cmxa" {"ast/ast.cmxa"}
  "_build/install/default/lib/Lua/ast/ast.ml" {"ast/ast.ml"}
  "_build/install/default/lib/Lua/dune-package"
  "_build/install/default/lib/Lua/opam"
]
libexec: [
  "_build/install/default/lib/Lua/Parser/parser.cmxs" {"Parser/parser.cmxs"}
  "_build/install/default/lib/Lua/ast/ast.cmxs" {"ast/ast.cmxs"}
]
doc: [
  "_build/install/default/doc/Lua/README.md"
]
